version: '3.7'
volumes:
  dbdata:
    driver: local
services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: "always"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'university'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - '3306'
  university:
    image: university:1.1.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: "no"
    entrypoint: ["bash", "-c", "java -jar university.jar --spring.profiles.active=dev"]


